[project]
name = "metadata-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lihil>=0.2.34",
    "uvicorn>=0.38.0",
]
